"""
safety.py — Crisis detection and safe response generation.

Isolation principle:
  - This module has NO dependency on the LLM or Streamlit.
  - It can be unit-tested completely independently.
  - The CRISIS_RESPONSE is hardcoded — it must never go through an LLM.
"""

from config import SAFETY_TRIGGERS

# ── Crisis Detection ───────────────────────────────────────────────────────────

def is_crisis_message(text: str) -> bool:
    """
    Return True if the user message contains crisis-related language.

    Uses simple substring matching — fast, predictable, no false negatives
    from model hallucination.
    """
    lowered = text.lower()
    return any(trigger in lowered for trigger in SAFETY_TRIGGERS)


# ── Safe Response ──────────────────────────────────────────────────────────────
# This response is NEVER generated by an LLM.
# It is always returned verbatim when a crisis is detected.

CRISIS_RESPONSE = """\
I'm really glad you reached out, and I hear you.

What you're sharing sounds very heavy, and you deserve real human support — not just a chat agent.

**Please reach out to a professional right now:**

- 🇮🇳 **iCall (India):** 9152987821
- 🌍 **Crisis Text Line:** Text HOME to 741741
- 📞 **International crisis centres:** https://www.iasp.info/resources/Crisis_Centres/
- 🆘 **Vandrevala Foundation (India, 24/7):** 1860-2662-345

You don't have to figure this out alone. Please take that step — you matter, and people are trained to help.

I'll be here when you're ready to talk more.
"""
